# Form implementation generated from reading ui file 'BuscarOfertas.ui'
#
# Created by: PyQt6 UI code generator 6.11.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_BuscarOfertas(object):
    def setupUi(self, Form):
        Form.setObjectName("frmBuscarOfertas")
        Form.resize(800, 600)
        Form.setMinimumSize(QtCore.QSize(800, 600))
        Form.setMaximumSize(QtCore.QSize(800, 600))
        Form.setWindowTitle("Buscar Ofertas de Prácticas")

        font_base = QtGui.QFont()
        font_base.setFamily("Segoe UI")
        font_base.setPointSize(11)

        self.lblTitulo = QtWidgets.QLabel(parent=Form)
        self.lblTitulo.setGeometry(QtCore.QRect(200, 10, 400, 40))
        font_titulo = QtGui.QFont()
        font_titulo.setFamily("Segoe UI")
        font_titulo.setPointSize(14)
        self.lblTitulo.setFont(font_titulo)
        self.lblTitulo.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lblTitulo.setText("Ofertas Disponibles")

        self.tblOfertas = QtWidgets.QTableWidget(parent=Form)
        self.tblOfertas.setGeometry(QtCore.QRect(20, 60, 760, 400))
        self.tblOfertas.setFont(font_base)
        self.tblOfertas.setColumnCount(5)
        self.tblOfertas.setHorizontalHeaderLabels(
            ["ID Oferta", "Empresa", "Puesto", "Descripción", "Fecha"])
        self.tblOfertas.setEditTriggers(QtWidgets.QAbstractItemView.EditTrigger.NoEditTriggers)
        self.tblOfertas.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectionBehavior.SelectRows)
        self.tblOfertas.setAlternatingRowColors(True)
        self.tblOfertas.horizontalHeader().setStretchLastSection(True)
        self.tblOfertas.horizontalHeader().setFont(font_base)

        self.lblIdOferta = QtWidgets.QLabel(parent=Form)
        self.lblIdOferta.setGeometry(QtCore.QRect(20, 490, 100, 30))
        self.lblIdOferta.setFont(font_base)
        self.lblIdOferta.setText("ID Oferta:")

        self.txtIdOferta = QtWidgets.QLineEdit(parent=Form)
        self.txtIdOferta.setGeometry(QtCore.QRect(130, 490, 200, 30))
        self.txtIdOferta.setFont(font_base)
        self.txtIdOferta.setPlaceholderText("Ingrese el ID")

        self.btnPostular = QtWidgets.QPushButton(parent=Form)
        self.btnPostular.setGeometry(QtCore.QRect(370, 490, 180, 35))
        font_btn = QtGui.QFont()
        font_btn.setFamily("Segoe UI")
        font_btn.setPointSize(11)
        self.btnPostular.setFont(font_btn)
        self.btnPostular.setText("Postularme")
        self.btnPostular.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))

        self.btnRefrescar = QtWidgets.QPushButton(parent=Form)
        self.btnRefrescar.setGeometry(QtCore.QRect(620, 545, 160, 35))
        self.btnRefrescar.setFont(font_base)
        self.btnRefrescar.setText("Refrescar Tabla")
        self.btnRefrescar.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
