# Form implementation generated from reading ui file 'MisPostulaciones.ui'
#
# Created by: PyQt6 UI code generator 6.11.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MisPostulaciones(object):
    def setupUi(self, Form):
        Form.setObjectName("frmMisPostulaciones")
        Form.resize(800, 600)
        Form.setMinimumSize(QtCore.QSize(800, 600))
        Form.setMaximumSize(QtCore.QSize(800, 600))
        Form.setWindowTitle("Mis Postulaciones")

        font_base = QtGui.QFont()
        font_base.setFamily("Segoe UI")
        font_base.setPointSize(11)

        self.lblTitulo = QtWidgets.QLabel(parent=Form)
        self.lblTitulo.setGeometry(QtCore.QRect(200, 10, 400, 40))
        font_titulo = QtGui.QFont()
        font_titulo.setFamily("Segoe UI")
        font_titulo.setPointSize(14)
        self.lblTitulo.setFont(font_titulo)
        self.lblTitulo.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lblTitulo.setText("Mis Postulaciones")

        self.tblMisPostulaciones = QtWidgets.QTableWidget(parent=Form)
        self.tblMisPostulaciones.setGeometry(QtCore.QRect(20, 60, 760, 470))
        self.tblMisPostulaciones.setFont(font_base)
        self.tblMisPostulaciones.setColumnCount(4)
        self.tblMisPostulaciones.setHorizontalHeaderLabels(
            ["ID Postulación", "Oferta", "Empresa", "Estado Validación"])
        self.tblMisPostulaciones.setEditTriggers(QtWidgets.QAbstractItemView.EditTrigger.NoEditTriggers)
        self.tblMisPostulaciones.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectionBehavior.SelectRows)
        self.tblMisPostulaciones.setAlternatingRowColors(True)
        self.tblMisPostulaciones.horizontalHeader().setStretchLastSection(True)
        self.tblMisPostulaciones.horizontalHeader().setFont(font_base)

        self.btnRefrescar = QtWidgets.QPushButton(parent=Form)
        self.btnRefrescar.setGeometry(QtCore.QRect(620, 550, 160, 35))
        self.btnRefrescar.setFont(font_base)
        self.btnRefrescar.setText("Refrescar")
        self.btnRefrescar.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
