# Form implementation generated from reading ui file 'Solicitudes.ui'
#
# Created by: PyQt6 UI code generator 6.11.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Solicitudes(object):
    def setupUi(self, Form):
        Form.setObjectName("frmSolicitudes")
        Form.resize(800, 600)
        Form.setMinimumSize(QtCore.QSize(800, 600))
        Form.setWindowTitle("Solicitudes Especiales")

        font_base = QtGui.QFont()
        font_base.setFamily("Segoe UI")
        font_base.setPointSize(11)

        self.lblTitulo = QtWidgets.QLabel(parent=Form)
        self.lblTitulo.setGeometry(QtCore.QRect(210, 10, 400, 40))
        font_titulo = QtGui.QFont()
        font_titulo.setFamily("Segoe UI")
        font_titulo.setPointSize(14)
        self.lblTitulo.setFont(font_titulo)
        self.lblTitulo.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lblTitulo.setText("Enviar Solicitud Especial")

        self.lblTipoSolicitud = QtWidgets.QLabel(parent=Form)
        self.lblTipoSolicitud.setGeometry(QtCore.QRect(20, 60, 150, 30))
        self.lblTipoSolicitud.setFont(font_base)
        self.lblTipoSolicitud.setText("Tipo de Solicitud:")

        self.cmbTipoSolicitud = QtWidgets.QComboBox(parent=Form)
        self.cmbTipoSolicitud.setGeometry(QtCore.QRect(180, 60, 400, 30))
        self.cmbTipoSolicitud.setFont(font_base)
        self.cmbTipoSolicitud.addItems([
            "Autorización de Empresa Propia",
            "Emisión de Certificado/Oficio"])

        self.lblMotivo = QtWidgets.QLabel(parent=Form)
        self.lblMotivo.setGeometry(QtCore.QRect(20, 100, 150, 30))
        self.lblMotivo.setFont(font_base)
        self.lblMotivo.setText("Motivo / Detalle:")

        self.txaMotivoDetalle = QtWidgets.QTextEdit(parent=Form)
        self.txaMotivoDetalle.setGeometry(QtCore.QRect(180, 100, 400, 90))
        self.txaMotivoDetalle.setFont(font_base)
        self.txaMotivoDetalle.setPlaceholderText("Describa el motivo de su solicitud...")

        self.grpEmpresa = QtWidgets.QGroupBox(parent=Form)
        self.grpEmpresa.setGeometry(QtCore.QRect(20, 200, 760, 180))
        self.grpEmpresa.setFont(font_base)
        self.grpEmpresa.setTitle("Datos de la empresa propia (solo si aplica)")
        layout = QtWidgets.QFormLayout(self.grpEmpresa)

        def fila(texto):
            lbl = QtWidgets.QLabel(texto, parent=self.grpEmpresa)
            lbl.setFont(font_base)
            campo = QtWidgets.QLineEdit(parent=self.grpEmpresa)
            campo.setFont(font_base)
            layout.addRow(lbl, campo)
            return campo

        self.txtEmpNombre = fila("Nombre empresa:")
        self.txtEmpRuc = fila("RUC:")
        self.txtEmpDireccion = fila("Dirección:")
        self.txtEmpTelefono = fila("Teléfono:")
        self.txtEmpEmail = fila("Email:")

        self.btnEnviarSolicitud = QtWidgets.QPushButton(parent=Form)
        self.btnEnviarSolicitud.setGeometry(QtCore.QRect(300, 388, 220, 36))
        font_btn = QtGui.QFont()
        font_btn.setFamily("Segoe UI")
        font_btn.setPointSize(11)
        self.btnEnviarSolicitud.setFont(font_btn)
        self.btnEnviarSolicitud.setText("Enviar Solicitud")
        self.btnEnviarSolicitud.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))

        self.tblSolicitudes = QtWidgets.QTableWidget(parent=Form)
        self.tblSolicitudes.setGeometry(QtCore.QRect(20, 432, 760, 160))
        self.tblSolicitudes.setFont(font_base)
        self.tblSolicitudes.setColumnCount(4)
        self.tblSolicitudes.setHorizontalHeaderLabels(["ID", "Tipo", "Estado", "Fecha"])
        self.tblSolicitudes.setEditTriggers(QtWidgets.QAbstractItemView.EditTrigger.NoEditTriggers)
        self.tblSolicitudes.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectionBehavior.SelectRows)
        self.tblSolicitudes.setAlternatingRowColors(True)
        self.tblSolicitudes.horizontalHeader().setStretchLastSection(True)
