# Form implementation generated from reading ui file 'AprobarFormulario1.ui'
#
# Created by: PyQt6 UI code generator 6.11.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_AprobarFormulario1(object):
    def setupUi(self, Form):
        Form.setObjectName("frmAprobarFormulario1")
        Form.resize(800, 600)
        Form.setMinimumSize(QtCore.QSize(800, 600))
        Form.setWindowTitle("Aprobar Formulario 1")

        font_base = QtGui.QFont()
        font_base.setFamily("Segoe UI")
        font_base.setPointSize(11)

        self.lblTitulo = QtWidgets.QLabel(parent=Form)
        self.lblTitulo.setGeometry(QtCore.QRect(210, 10, 400, 40))
        font_titulo = QtGui.QFont()
        font_titulo.setFamily("Segoe UI")
        font_titulo.setPointSize(14)
        self.lblTitulo.setFont(font_titulo)
        self.lblTitulo.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lblTitulo.setText("Formularios 1 por Aprobar")

        self.tblPendientes = QtWidgets.QTableWidget(parent=Form)
        self.tblPendientes.setGeometry(QtCore.QRect(20, 60, 760, 220))
        self.tblPendientes.setFont(font_base)
        self.tblPendientes.setColumnCount(6)
        self.tblPendientes.setHorizontalHeaderLabels(
            ["ID Práctica", "Estudiante", "Empresa", "Tipo Práctica", "Horas", "Estado F1"])
        self.tblPendientes.setEditTriggers(QtWidgets.QAbstractItemView.EditTrigger.NoEditTriggers)
        self.tblPendientes.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectionBehavior.SelectRows)
        self.tblPendientes.setAlternatingRowColors(True)
        self.tblPendientes.horizontalHeader().setStretchLastSection(True)

        self.lblDetalle = QtWidgets.QLabel(parent=Form)
        self.lblDetalle.setGeometry(QtCore.QRect(20, 290, 400, 25))
        self.lblDetalle.setFont(font_base)
        self.lblDetalle.setText("Detalle del Formulario 1:")

        self.txaDetalle = QtWidgets.QTextEdit(parent=Form)
        self.txaDetalle.setGeometry(QtCore.QRect(20, 318, 760, 220))
        self.txaDetalle.setFont(font_base)
        self.txaDetalle.setReadOnly(True)

        self.lblIdPractica = QtWidgets.QLabel(parent=Form)
        self.lblIdPractica.setGeometry(QtCore.QRect(20, 552, 90, 30))
        self.lblIdPractica.setFont(font_base)
        self.lblIdPractica.setText("ID Práctica:")
        self.txtIdPractica = QtWidgets.QLineEdit(parent=Form)
        self.txtIdPractica.setGeometry(QtCore.QRect(110, 552, 110, 30))
        self.txtIdPractica.setFont(font_base)
        self.txtIdPractica.setPlaceholderText("ID")

        font_btn = QtGui.QFont()
        font_btn.setFamily("Segoe UI")
        font_btn.setPointSize(11)

        self.btnVerDetalle = QtWidgets.QPushButton(parent=Form)
        self.btnVerDetalle.setGeometry(QtCore.QRect(240, 552, 150, 32))
        self.btnVerDetalle.setFont(font_base)
        self.btnVerDetalle.setText("Ver Detalle")
        self.btnVerDetalle.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))

        self.btnAprobar = QtWidgets.QPushButton(parent=Form)
        self.btnAprobar.setGeometry(QtCore.QRect(400, 552, 190, 32))
        self.btnAprobar.setFont(font_btn)
        self.btnAprobar.setText("Aprobar Formulario 1")
        self.btnAprobar.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))

        self.btnRefrescar = QtWidgets.QPushButton(parent=Form)
        self.btnRefrescar.setGeometry(QtCore.QRect(600, 552, 180, 32))
        self.btnRefrescar.setFont(font_base)
        self.btnRefrescar.setText("Refrescar")
        self.btnRefrescar.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
