# Form implementation generated from reading ui file 'Formulario3.ui'
#
# Created by: PyQt6 UI code generator 6.11.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Formulario3(object):
    def setupUi(self, Form):
        Form.setObjectName("frmFormulario3")
        Form.resize(860, 760)
        Form.setMinimumSize(QtCore.QSize(860, 760))
        Form.setWindowTitle("Formulario 3 - Evaluación Académica")

        font_base = QtGui.QFont()
        font_base.setFamily("Segoe UI")
        font_base.setPointSize(11)

        self.lblTitulo = QtWidgets.QLabel(parent=Form)
        self.lblTitulo.setGeometry(QtCore.QRect(230, 8, 400, 36))
        font_titulo = QtGui.QFont()
        font_titulo.setFamily("Segoe UI")
        font_titulo.setPointSize(14)
        self.lblTitulo.setFont(font_titulo)
        self.lblTitulo.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lblTitulo.setText("Formulario 3 - Evaluación Académica")

        self.cabecera = QtWidgets.QWidget(parent=Form)
        self.cabecera.setGeometry(QtCore.QRect(20, 46, 820, 120))
        layout = QtWidgets.QFormLayout(self.cabecera)
        layout.setContentsMargins(0, 0, 0, 0)

        def solo_lectura(texto):
            lbl = QtWidgets.QLabel(texto, parent=self.cabecera)
            lbl.setFont(font_base)
            val = QtWidgets.QLabel("", parent=self.cabecera)
            val.setFont(font_base)
            layout.addRow(lbl, val)
            return val

        self.lblEstudianteVal = solo_lectura("Estudiante:")
        self.lblEmpresaVal = solo_lectura("Empresa Oferente:")
        self.lblTutorAcadVal = solo_lectura("Tutor Académico:")
        self.lblCarreraVal = solo_lectura("Carrera:")
        self.lblFechasHorasVal = solo_lectura("Fechas y Horas:")

        self.lblPractica = QtWidgets.QLabel(parent=Form)
        self.lblPractica.setGeometry(QtCore.QRect(20, 172, 120, 30))
        self.lblPractica.setFont(font_base)
        self.lblPractica.setText("ID Práctica:")
        self.txtIdPractica = QtWidgets.QLineEdit(parent=Form)
        self.txtIdPractica.setGeometry(QtCore.QRect(140, 172, 130, 30))
        self.txtIdPractica.setFont(font_base)
        self.txtIdPractica.setPlaceholderText("ID")
        self.btnCargar = QtWidgets.QPushButton(parent=Form)
        self.btnCargar.setGeometry(QtCore.QRect(290, 172, 130, 30))
        self.btnCargar.setFont(font_base)
        self.btnCargar.setText("Cargar Datos")
        self.btnCargar.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))

        self.lblCampo = QtWidgets.QLabel(parent=Form)
        self.lblCampo.setGeometry(QtCore.QRect(20, 212, 130, 28))
        self.lblCampo.setFont(font_base)
        self.lblCampo.setText("Campo ocupacional:")
        self.txtCampoOcupacional = QtWidgets.QLineEdit(parent=Form)
        self.txtCampoOcupacional.setGeometry(QtCore.QRect(160, 212, 400, 28))
        self.txtCampoOcupacional.setFont(font_base)

        self.lblCalificacion = QtWidgets.QLabel(parent=Form)
        self.lblCalificacion.setGeometry(QtCore.QRect(580, 212, 160, 28))
        self.lblCalificacion.setFont(font_base)
        self.lblCalificacion.setText("Calificación / 100:")
        self.spnCalificacion = QtWidgets.QSpinBox(parent=Form)
        self.spnCalificacion.setGeometry(QtCore.QRect(740, 212, 100, 28))
        self.spnCalificacion.setFont(font_base)
        self.spnCalificacion.setMaximum(100)

        self.tblRubricaAcademica = QtWidgets.QTableWidget(parent=Form)
        self.tblRubricaAcademica.setGeometry(QtCore.QRect(20, 250, 820, 400))
        self.tblRubricaAcademica.setFont(font_base)
        self.tblRubricaAcademica.setColumnCount(4)
        self.tblRubricaAcademica.setHorizontalHeaderLabels(
            ["Criterio", "Nivel Esperado", "No Aplica", "Nivel Alcanzado"])
        self.tblRubricaAcademica.setColumnWidth(0, 480)
        self.tblRubricaAcademica.setColumnWidth(1, 110)
        self.tblRubricaAcademica.setColumnWidth(2, 80)
        self.tblRubricaAcademica.setColumnWidth(3, 140)
        self.tblRubricaAcademica.setEditTriggers(QtWidgets.QAbstractItemView.EditTrigger.NoEditTriggers)
        self.tblRubricaAcademica.setWordWrap(True)

        font_btn = QtGui.QFont()
        font_btn.setFamily("Segoe UI")
        font_btn.setPointSize(11)

        self.btnGuardarFormulario3 = QtWidgets.QPushButton(parent=Form)
        self.btnGuardarFormulario3.setGeometry(QtCore.QRect(220, 665, 200, 40))
        self.btnGuardarFormulario3.setFont(font_btn)
        self.btnGuardarFormulario3.setText("Guardar Formulario 3")
        self.btnGuardarFormulario3.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))

        self.btnAsentarNota = QtWidgets.QPushButton(parent=Form)
        self.btnAsentarNota.setGeometry(QtCore.QRect(440, 665, 200, 40))
        self.btnAsentarNota.setFont(font_btn)
        self.btnAsentarNota.setText("Asentar Nota")
        self.btnAsentarNota.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))

        self.btnLimpiar = QtWidgets.QPushButton(parent=Form)
        self.btnLimpiar.setGeometry(QtCore.QRect(660, 665, 180, 40))
        self.btnLimpiar.setFont(font_btn)
        self.btnLimpiar.setText("Limpiar")
        self.btnLimpiar.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
