# Form implementation generated from reading ui file 'VistaTutorAcademicoPrincipal.ui'
#
# Created by: PyQt6 UI code generator 6.11.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_frmTutorAcademico(object):
    def setupUi(self, frmTutorAcademico):
        frmTutorAcademico.setObjectName("frmTutorAcademico")
        frmTutorAcademico.resize(800, 600)
        frmTutorAcademico.setWindowTitle("Coordinador / Tutor Académico")

        self.centralwidget = QtWidgets.QWidget(parent=frmTutorAcademico)
        self.lblImagen = QtWidgets.QLabel(parent=self.centralwidget)
        self.lblImagen.setGeometry(QtCore.QRect(220, 140, 361, 341))
        self.lblImagen.setText("")
        self.lblImagen.setScaledContents(True)

        self.widget = QtWidgets.QWidget(parent=self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(0, 90, 801, 33))
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.addItem(QtWidgets.QSpacerItem(
            40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum))
        self.lblTitulo = QtWidgets.QLabel(parent=self.widget)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        self.lblTitulo.setFont(font)
        self.lblTitulo.setText("Panel del Tutor Académico")
        self.horizontalLayout.addWidget(self.lblTitulo)
        self.horizontalLayout.addItem(QtWidgets.QSpacerItem(
            40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum))
        frmTutorAcademico.setCentralWidget(self.centralwidget)

        self.menubar = QtWidgets.QMenuBar(parent=frmTutorAcademico)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 31))
        font_menu = QtGui.QFont()
        font_menu.setPointSize(11)
        self.menubar.setFont(font_menu)
        self.mnuPracticas = QtWidgets.QMenu(parent=self.menubar)
        self.mnuPracticas.setTitle("Prácticas")
        self.mnuSistema = QtWidgets.QMenu(parent=self.menubar)
        self.mnuSistema.setTitle("Sistema")
        frmTutorAcademico.setMenuBar(self.menubar)

        self.statusbar = QtWidgets.QStatusBar(parent=frmTutorAcademico)
        frmTutorAcademico.setStatusBar(self.statusbar)
        self.tlbPrincipal = QtWidgets.QToolBar(parent=frmTutorAcademico)
        frmTutorAcademico.addToolBar(QtCore.Qt.ToolBarArea.TopToolBarArea, self.tlbPrincipal)

        self.actAprobarF1 = QtGui.QAction(parent=frmTutorAcademico)
        self.actAprobarF1.setText("Aprobar Formulario 1")
        self.actFormulario3 = QtGui.QAction(parent=frmTutorAcademico)
        self.actFormulario3.setText("Evaluación Académica")
        self.actListarPracticas = QtGui.QAction(parent=frmTutorAcademico)
        self.actListarPracticas.setText("Listar Prácticas Activas")
        self.actInformacion = QtGui.QAction(parent=frmTutorAcademico)
        self.actInformacion.setText("Información")
        self.actSalir = QtGui.QAction(parent=frmTutorAcademico)
        self.actSalir.setText("Salir")

        self.mnuPracticas.addAction(self.actListarPracticas)
        self.mnuPracticas.addAction(self.actAprobarF1)
        self.mnuPracticas.addAction(self.actFormulario3)
        self.mnuSistema.addAction(self.actInformacion)
        self.mnuSistema.addSeparator()
        self.mnuSistema.addAction(self.actSalir)
        self.menubar.addAction(self.mnuSistema.menuAction())
        self.menubar.addAction(self.mnuPracticas.menuAction())

        self.tlbPrincipal.addAction(self.actListarPracticas)
        self.tlbPrincipal.addAction(self.actAprobarF1)
        self.tlbPrincipal.addAction(self.actFormulario3)

        QtCore.QMetaObject.connectSlotsByName(frmTutorAcademico)
