# Form implementation generated from reading ui file 'ArmarTernas.ui'
#
# Created by: PyQt6 UI code generator 6.11.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_ArmarTernas(object):
    def setupUi(self, Form):
        Form.setObjectName("frmArmarTernas")
        Form.resize(800, 600)
        Form.setMinimumSize(QtCore.QSize(800, 600))
        Form.setMaximumSize(QtCore.QSize(800, 600))
        Form.setWindowTitle("Armar Ternas")

        font_base = QtGui.QFont()
        font_base.setFamily("Segoe UI")
        font_base.setPointSize(11)

        self.lblTitulo = QtWidgets.QLabel(parent=Form)
        self.lblTitulo.setGeometry(QtCore.QRect(250, 10, 300, 40))
        font_titulo = QtGui.QFont()
        font_titulo.setFamily("Segoe UI")
        font_titulo.setPointSize(14)
        self.lblTitulo.setFont(font_titulo)
        self.lblTitulo.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lblTitulo.setText("Armar Terna de Postulantes")

        self.lblOferta = QtWidgets.QLabel(parent=Form)
        self.lblOferta.setGeometry(QtCore.QRect(20, 60, 140, 30))
        self.lblOferta.setFont(font_base)
        self.lblOferta.setText("Seleccionar Oferta:")

        self.cmbOfertas = QtWidgets.QComboBox(parent=Form)
        self.cmbOfertas.setGeometry(QtCore.QRect(170, 60, 600, 30))
        self.cmbOfertas.setFont(font_base)

        self.tblPostulaciones = QtWidgets.QTableWidget(parent=Form)
        self.tblPostulaciones.setGeometry(QtCore.QRect(20, 110, 760, 300))
        self.tblPostulaciones.setFont(font_base)
        self.tblPostulaciones.setColumnCount(5)
        self.tblPostulaciones.setHorizontalHeaderLabels(
            ["ID Postulación", "Cédula", "Nombres", "Ciclo", "Estado"])
        self.tblPostulaciones.setEditTriggers(QtWidgets.QAbstractItemView.EditTrigger.NoEditTriggers)
        self.tblPostulaciones.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectionBehavior.SelectRows)
        self.tblPostulaciones.setAlternatingRowColors(True)
        self.tblPostulaciones.horizontalHeader().setStretchLastSection(True)
        self.tblPostulaciones.horizontalHeader().setFont(font_base)

        self.lblPostulante1 = QtWidgets.QLabel(parent=Form)
        self.lblPostulante1.setGeometry(QtCore.QRect(20, 430, 110, 30))
        self.lblPostulante1.setFont(font_base)
        self.lblPostulante1.setText("Postulante 1:")

        self.txtIdPostulante1 = QtWidgets.QLineEdit(parent=Form)
        self.txtIdPostulante1.setGeometry(QtCore.QRect(140, 430, 120, 30))
        self.txtIdPostulante1.setFont(font_base)
        self.txtIdPostulante1.setPlaceholderText("ID Post.")

        self.lblPostulante2 = QtWidgets.QLabel(parent=Form)
        self.lblPostulante2.setGeometry(QtCore.QRect(280, 430, 110, 30))
        self.lblPostulante2.setFont(font_base)
        self.lblPostulante2.setText("Postulante 2:")

        self.txtIdPostulante2 = QtWidgets.QLineEdit(parent=Form)
        self.txtIdPostulante2.setGeometry(QtCore.QRect(400, 430, 120, 30))
        self.txtIdPostulante2.setFont(font_base)
        self.txtIdPostulante2.setPlaceholderText("ID Post.")

        self.lblPostulante3 = QtWidgets.QLabel(parent=Form)
        self.lblPostulante3.setGeometry(QtCore.QRect(540, 430, 110, 30))
        self.lblPostulante3.setFont(font_base)
        self.lblPostulante3.setText("Postulante 3:")

        self.txtIdPostulante3 = QtWidgets.QLineEdit(parent=Form)
        self.txtIdPostulante3.setGeometry(QtCore.QRect(660, 430, 110, 30))
        self.txtIdPostulante3.setFont(font_base)
        self.txtIdPostulante3.setPlaceholderText("ID Post.")

        self.btnEnviarTerna = QtWidgets.QPushButton(parent=Form)
        self.btnEnviarTerna.setGeometry(QtCore.QRect(280, 490, 240, 40))
        font_btn = QtGui.QFont()
        font_btn.setFamily("Segoe UI")
        font_btn.setPointSize(11)
        self.btnEnviarTerna.setFont(font_btn)
        self.btnEnviarTerna.setText("Enviar Terna a Empresa")
        self.btnEnviarTerna.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))

        self.btnRefrescarTernas = QtWidgets.QPushButton(parent=Form)
        self.btnRefrescarTernas.setGeometry(QtCore.QRect(620, 550, 160, 35))
        self.btnRefrescarTernas.setFont(font_base)
        self.btnRefrescarTernas.setText("Refrescar Tabla")
        self.btnRefrescarTernas.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
