# Form implementation generated from reading ui file 'BandejaSolicitudes.ui'
#
# Created by: PyQt6 UI code generator 6.11.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_BandejaSolicitudes(object):
    def setupUi(self, Form):
        Form.setObjectName("frmBandejaSolicitudes")
        Form.resize(800, 600)
        Form.setMinimumSize(QtCore.QSize(800, 600))
        Form.setWindowTitle("Bandeja de Solicitudes")

        font_base = QtGui.QFont()
        font_base.setFamily("Segoe UI")
        font_base.setPointSize(11)

        self.lblTitulo = QtWidgets.QLabel(parent=Form)
        self.lblTitulo.setGeometry(QtCore.QRect(210, 10, 400, 40))
        font_titulo = QtGui.QFont()
        font_titulo.setFamily("Segoe UI")
        font_titulo.setPointSize(14)
        self.lblTitulo.setFont(font_titulo)
        self.lblTitulo.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lblTitulo.setText("Bandeja de Solicitudes Especiales")

        self.tblSolicitudes = QtWidgets.QTableWidget(parent=Form)
        self.tblSolicitudes.setGeometry(QtCore.QRect(20, 60, 760, 400))
        self.tblSolicitudes.setFont(font_base)
        self.tblSolicitudes.setColumnCount(6)
        self.tblSolicitudes.setHorizontalHeaderLabels(
            ["ID", "Tipo", "Estudiante", "Motivo", "Estado", "Fecha"])
        self.tblSolicitudes.setEditTriggers(QtWidgets.QAbstractItemView.EditTrigger.NoEditTriggers)
        self.tblSolicitudes.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectionBehavior.SelectRows)
        self.tblSolicitudes.setAlternatingRowColors(True)
        self.tblSolicitudes.horizontalHeader().setStretchLastSection(True)

        self.lblIdSolicitud = QtWidgets.QLabel(parent=Form)
        self.lblIdSolicitud.setGeometry(QtCore.QRect(20, 480, 120, 30))
        self.lblIdSolicitud.setFont(font_base)
        self.lblIdSolicitud.setText("ID Solicitud:")

        self.txtIdSolicitud = QtWidgets.QLineEdit(parent=Form)
        self.txtIdSolicitud.setGeometry(QtCore.QRect(150, 480, 180, 30))
        self.txtIdSolicitud.setFont(font_base)
        self.txtIdSolicitud.setPlaceholderText("Ingrese el ID")

        font_btn = QtGui.QFont()
        font_btn.setFamily("Segoe UI")
        font_btn.setPointSize(11)

        self.btnAprobar = QtWidgets.QPushButton(parent=Form)
        self.btnAprobar.setGeometry(QtCore.QRect(360, 480, 200, 35))
        self.btnAprobar.setFont(font_btn)
        self.btnAprobar.setText("Aprobar / Registrar")
        self.btnAprobar.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))

        self.btnRechazar = QtWidgets.QPushButton(parent=Form)
        self.btnRechazar.setGeometry(QtCore.QRect(580, 480, 200, 35))
        self.btnRechazar.setFont(font_btn)
        self.btnRechazar.setText("Rechazar")
        self.btnRechazar.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))

        self.btnRefrescar = QtWidgets.QPushButton(parent=Form)
        self.btnRefrescar.setGeometry(QtCore.QRect(620, 530, 160, 35))
        self.btnRefrescar.setFont(font_base)
        self.btnRefrescar.setText("Refrescar Tabla")
        self.btnRefrescar.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
