# Form implementation generated from reading ui file 'GestionarEmpresas.ui'
#
# Created by: PyQt6 UI code generator 6.11.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_GestionarEmpresas(object):
    def setupUi(self, Form):
        Form.setObjectName("frmGestionarEmpresas")
        Form.resize(800, 600)
        Form.setMinimumSize(QtCore.QSize(800, 600))
        Form.setWindowTitle("Gestionar Empresas (Tutores Empresariales)")

        font_base = QtGui.QFont()
        font_base.setFamily("Segoe UI")
        font_base.setPointSize(11)

        self.lblTitulo = QtWidgets.QLabel(parent=Form)
        self.lblTitulo.setGeometry(QtCore.QRect(150, 10, 500, 40))
        font_titulo = QtGui.QFont()
        font_titulo.setFamily("Segoe UI")
        font_titulo.setPointSize(14)
        self.lblTitulo.setFont(font_titulo)
        self.lblTitulo.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lblTitulo.setText("Registrar Empresa / Tutor Empresarial")

        self.contenedorForm = QtWidgets.QWidget(parent=Form)
        self.contenedorForm.setGeometry(QtCore.QRect(20, 55, 760, 250))
        layout = QtWidgets.QFormLayout(self.contenedorForm)
        layout.setContentsMargins(0, 0, 0, 0)

        def fila(texto):
            lbl = QtWidgets.QLabel(texto, parent=self.contenedorForm)
            lbl.setFont(font_base)
            campo = QtWidgets.QLineEdit(parent=self.contenedorForm)
            campo.setFont(font_base)
            layout.addRow(lbl, campo)
            return campo

        self.txtCedula = fila("Cédula del tutor:")
        self.txtContrasena = fila("Contraseña:")
        self.txtNombres = fila("Nombres:")
        self.txtApellidos = fila("Apellidos:")
        self.txtTelefono = fila("Teléfono:")
        self.txtEmail = fila("Email:")
        self.txtCargo = fila("Cargo:")
        self.txtRUC = fila("RUC empresa:")
        self.txtNombreEmpresa = fila("Nombre empresa:")
        self.txtDireccionEmpresa = fila("Dirección empresa:")

        font_btn = QtGui.QFont()
        font_btn.setFamily("Segoe UI")
        font_btn.setPointSize(11)

        self.btnGuardar = QtWidgets.QPushButton(parent=Form)
        self.btnGuardar.setGeometry(QtCore.QRect(470, 312, 150, 35))
        self.btnGuardar.setFont(font_btn)
        self.btnGuardar.setText("Registrar")
        self.btnGuardar.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))

        self.btnLimpiar = QtWidgets.QPushButton(parent=Form)
        self.btnLimpiar.setGeometry(QtCore.QRect(630, 312, 150, 35))
        self.btnLimpiar.setFont(font_base)
        self.btnLimpiar.setText("Limpiar")
        self.btnLimpiar.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))

        self.tblEmpresas = QtWidgets.QTableWidget(parent=Form)
        self.tblEmpresas.setGeometry(QtCore.QRect(20, 355, 760, 190))
        self.tblEmpresas.setFont(font_base)
        self.tblEmpresas.setColumnCount(6)
        self.tblEmpresas.setHorizontalHeaderLabels(
            ["Cédula", "Tutor", "Cargo", "RUC", "Empresa", "Email"])
        self.tblEmpresas.setEditTriggers(QtWidgets.QAbstractItemView.EditTrigger.NoEditTriggers)
        self.tblEmpresas.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectionBehavior.SelectRows)
        self.tblEmpresas.setAlternatingRowColors(True)
        self.tblEmpresas.horizontalHeader().setStretchLastSection(True)

        self.txtEliminarCedula = QtWidgets.QLineEdit(parent=Form)
        self.txtEliminarCedula.setGeometry(QtCore.QRect(20, 553, 440, 35))
        self.txtEliminarCedula.setFont(font_base)
        self.txtEliminarCedula.setPlaceholderText("Cédula a eliminar")

        self.btnEliminar = QtWidgets.QPushButton(parent=Form)
        self.btnEliminar.setGeometry(QtCore.QRect(470, 553, 150, 35))
        self.btnEliminar.setFont(font_btn)
        self.btnEliminar.setText("Eliminar")
        self.btnEliminar.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))

        self.btnRefrescar = QtWidgets.QPushButton(parent=Form)
        self.btnRefrescar.setGeometry(QtCore.QRect(630, 553, 150, 35))
        self.btnRefrescar.setFont(font_base)
        self.btnRefrescar.setText("Refrescar")
        self.btnRefrescar.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
