# Form implementation generated from reading ui file 'ListarEstudiantes.ui'
#
# Created by: PyQt6 UI code generator 6.11.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_ListarEstudiantes(object):
    def setupUi(self, Form):
        Form.setObjectName("frmListarEstudiantes")
        Form.resize(800, 600)
        Form.setMinimumSize(QtCore.QSize(800, 600))
        Form.setWindowTitle("Estudiantes")

        font_base = QtGui.QFont()
        font_base.setFamily("Segoe UI")
        font_base.setPointSize(11)

        self.lblTitulo = QtWidgets.QLabel(parent=Form)
        self.lblTitulo.setGeometry(QtCore.QRect(200, 10, 400, 40))
        font_titulo = QtGui.QFont()
        font_titulo.setFamily("Segoe UI")
        font_titulo.setPointSize(14)
        self.lblTitulo.setFont(font_titulo)
        self.lblTitulo.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lblTitulo.setText("Estado de los Estudiantes")

        self.tblEstudiantes = QtWidgets.QTableWidget(parent=Form)
        self.tblEstudiantes.setGeometry(QtCore.QRect(20, 60, 760, 470))
        self.tblEstudiantes.setFont(font_base)
        self.tblEstudiantes.setColumnCount(7)
        self.tblEstudiantes.setHorizontalHeaderLabels(
            ["Cédula", "Nombres", "Apellidos", "Carrera", "Ciclo", "Prácticas", "Horas realizadas"])
        self.tblEstudiantes.setColumnWidth(0, 100)
        self.tblEstudiantes.setColumnWidth(1, 150)
        self.tblEstudiantes.setColumnWidth(2, 150)
        self.tblEstudiantes.setColumnWidth(3, 130)
        self.tblEstudiantes.setColumnWidth(4, 60)
        self.tblEstudiantes.setColumnWidth(5, 80)
        self.tblEstudiantes.setEditTriggers(QtWidgets.QAbstractItemView.EditTrigger.NoEditTriggers)
        self.tblEstudiantes.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectionBehavior.SelectRows)
        self.tblEstudiantes.setAlternatingRowColors(True)
        self.tblEstudiantes.horizontalHeader().setStretchLastSection(True)

        self.btnRefrescar = QtWidgets.QPushButton(parent=Form)
        self.btnRefrescar.setGeometry(QtCore.QRect(620, 545, 160, 35))
        self.btnRefrescar.setFont(font_base)
        self.btnRefrescar.setText("Refrescar")
        self.btnRefrescar.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
