# Form implementation generated from reading ui file 'ValidarPostulaciones.ui'
#
# Created by: PyQt6 UI code generator 6.11.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_ValidarPostulaciones(object):
    def setupUi(self, Form):
        Form.setObjectName("frmValidarPostulaciones")
        Form.resize(800, 600)
        Form.setMinimumSize(QtCore.QSize(800, 600))
        Form.setMaximumSize(QtCore.QSize(800, 600))
        Form.setWindowTitle("Validar Postulaciones")

        font_base = QtGui.QFont()
        font_base.setFamily("Segoe UI")
        font_base.setPointSize(11)

        self.lblTitulo = QtWidgets.QLabel(parent=Form)
        self.lblTitulo.setGeometry(QtCore.QRect(200, 10, 400, 40))
        font_titulo = QtGui.QFont()
        font_titulo.setFamily("Segoe UI")
        font_titulo.setPointSize(14)
        self.lblTitulo.setFont(font_titulo)
        self.lblTitulo.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lblTitulo.setText("Validación de Postulaciones")

        self.tblPostulaciones = QtWidgets.QTableWidget(parent=Form)
        self.tblPostulaciones.setGeometry(QtCore.QRect(20, 60, 760, 400))
        self.tblPostulaciones.setFont(font_base)
        self.tblPostulaciones.setColumnCount(7)
        self.tblPostulaciones.setHorizontalHeaderLabels(
            ["ID Postulación", "Cédula Estudiante", "Nombres", "Ciclo",
             "Prácticas Previas", "Empresa/Oferta", "Estado"])
        self.tblPostulaciones.setEditTriggers(QtWidgets.QAbstractItemView.EditTrigger.NoEditTriggers)
        self.tblPostulaciones.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectionBehavior.SelectRows)
        self.tblPostulaciones.setAlternatingRowColors(True)
        self.tblPostulaciones.horizontalHeader().setStretchLastSection(True)
        self.tblPostulaciones.horizontalHeader().setFont(font_base)

        self.lblIdPostulacion = QtWidgets.QLabel(parent=Form)
        self.lblIdPostulacion.setGeometry(QtCore.QRect(20, 490, 130, 30))
        self.lblIdPostulacion.setFont(font_base)
        self.lblIdPostulacion.setText("ID Postulación:")

        self.txtIdPostulacion = QtWidgets.QLineEdit(parent=Form)
        self.txtIdPostulacion.setGeometry(QtCore.QRect(160, 490, 200, 30))
        self.txtIdPostulacion.setFont(font_base)
        self.txtIdPostulacion.setPlaceholderText("Ingrese el ID")

        self.btnAprobar = QtWidgets.QPushButton(parent=Form)
        self.btnAprobar.setGeometry(QtCore.QRect(420, 490, 160, 35))
        font_btn = QtGui.QFont()
        font_btn.setFamily("Segoe UI")
        font_btn.setPointSize(11)
        self.btnAprobar.setFont(font_btn)
        self.btnAprobar.setText("Aprobar")
        self.btnAprobar.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))

        self.btnRechazar = QtWidgets.QPushButton(parent=Form)
        self.btnRechazar.setGeometry(QtCore.QRect(610, 490, 160, 35))
        self.btnRechazar.setFont(font_btn)
        self.btnRechazar.setText("Rechazar")
        self.btnRechazar.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))

        self.btnRefrescar = QtWidgets.QPushButton(parent=Form)
        self.btnRefrescar.setGeometry(QtCore.QRect(620, 540, 160, 35))
        self.btnRefrescar.setFont(font_base)
        self.btnRefrescar.setText("Refrescar Tabla")
        self.btnRefrescar.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
