# Form implementation generated from reading ui file 'VistaCoordinadorVinculacionPrincipal.ui'
#
# Created by: PyQt6 UI code generator 6.11.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_frmVinculacion(object):
    def setupUi(self, frmVinculacion):
        frmVinculacion.setObjectName("frmVinculacion")
        frmVinculacion.resize(800, 600)
        frmVinculacion.setWindowTitle("Coordinador de Vinculación")

        self.centralwidget = QtWidgets.QWidget(parent=frmVinculacion)
        self.centralwidget.setObjectName("centralwidget")

        self.lblImagen = QtWidgets.QLabel(parent=self.centralwidget)
        self.lblImagen.setGeometry(QtCore.QRect(220, 140, 361, 341))
        self.lblImagen.setText("")
        self.lblImagen.setScaledContents(True)

        self.widget = QtWidgets.QWidget(parent=self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(0, 90, 801, 33))
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.addItem(QtWidgets.QSpacerItem(
            40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum))
        self.lblTitulo = QtWidgets.QLabel(parent=self.widget)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        self.lblTitulo.setFont(font)
        self.lblTitulo.setText("Sistema de Coordinación de Vinculación")
        self.horizontalLayout.addWidget(self.lblTitulo)
        self.horizontalLayout.addItem(QtWidgets.QSpacerItem(
            40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum))
        frmVinculacion.setCentralWidget(self.centralwidget)

        self.menubar = QtWidgets.QMenuBar(parent=frmVinculacion)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 31))
        font_menu = QtGui.QFont()
        font_menu.setPointSize(11)
        self.menubar.setFont(font_menu)
        self.mnuPostulaciones = QtWidgets.QMenu(parent=self.menubar)
        self.mnuPostulaciones.setTitle("Postulación")
        self.mnuEmpresa = QtWidgets.QMenu(parent=self.menubar)
        self.mnuEmpresa.setTitle("Empresa")
        self.mnuTramites = QtWidgets.QMenu(parent=self.menubar)
        self.mnuTramites.setTitle("Trámites")
        self.mnuSistema = QtWidgets.QMenu(parent=self.menubar)
        self.mnuSistema.setTitle("Sistema")
        frmVinculacion.setMenuBar(self.menubar)

        self.statusbar = QtWidgets.QStatusBar(parent=frmVinculacion)
        frmVinculacion.setStatusBar(self.statusbar)
        self.tlbPrincipal = QtWidgets.QToolBar(parent=frmVinculacion)
        frmVinculacion.addToolBar(QtCore.Qt.ToolBarArea.TopToolBarArea, self.tlbPrincipal)

        self.actValidarPostulacion = QtGui.QAction(parent=frmVinculacion)
        self.actValidarPostulacion.setText("Validar Postulación")
        self.actArmarTerna = QtGui.QAction(parent=frmVinculacion)
        self.actArmarTerna.setText("Armar Terna")
        self.actListarEstudiantes = QtGui.QAction(parent=frmVinculacion)
        self.actListarEstudiantes.setText("Listar Estudiantes")
        self.actGestionarEmpresa = QtGui.QAction(parent=frmVinculacion)
        self.actGestionarEmpresa.setText("Gestionar Empresas")
        self.actBandejaSolicitudes = QtGui.QAction(parent=frmVinculacion)
        self.actBandejaSolicitudes.setText("Bandeja de Solicitudes")
        self.actInformacion = QtGui.QAction(parent=frmVinculacion)
        self.actInformacion.setText("Información")
        self.actSalir = QtGui.QAction(parent=frmVinculacion)
        self.actSalir.setText("Salir")

        self.mnuPostulaciones.addAction(self.actValidarPostulacion)
        self.mnuPostulaciones.addAction(self.actArmarTerna)
        self.mnuPostulaciones.addAction(self.actListarEstudiantes)
        self.mnuEmpresa.addAction(self.actGestionarEmpresa)
        self.mnuTramites.addAction(self.actBandejaSolicitudes)
        self.mnuSistema.addAction(self.actInformacion)
        self.mnuSistema.addSeparator()
        self.mnuSistema.addAction(self.actSalir)
        self.menubar.addAction(self.mnuSistema.menuAction())
        self.menubar.addAction(self.mnuPostulaciones.menuAction())
        self.menubar.addAction(self.mnuEmpresa.menuAction())
        self.menubar.addAction(self.mnuTramites.menuAction())

        self.tlbPrincipal.addAction(self.actValidarPostulacion)
        self.tlbPrincipal.addAction(self.actArmarTerna)
        self.tlbPrincipal.addAction(self.actListarEstudiantes)
        self.tlbPrincipal.addAction(self.actGestionarEmpresa)
        self.tlbPrincipal.addAction(self.actBandejaSolicitudes)

        QtCore.QMetaObject.connectSlotsByName(frmVinculacion)
