# Form implementation generated from reading ui file 'CrudAdministrador.ui'
#
# Created by: PyQt6 UI code generator 6.11.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_CrudAdministrador(object):
    def setupUi(self, Form):
        Form.setObjectName("frmCrudAdministrador")
        Form.resize(800, 600)
        Form.setMinimumSize(QtCore.QSize(800, 600))
        Form.setWindowTitle("Mantenimiento de Administradores")

        font_base = QtGui.QFont()
        font_base.setFamily("Segoe UI")
        font_base.setPointSize(11)

        self.lblTitulo = QtWidgets.QLabel(parent=Form)
        self.lblTitulo.setGeometry(QtCore.QRect(200, 10, 400, 40))
        font_titulo = QtGui.QFont()
        font_titulo.setFamily("Segoe UI")
        font_titulo.setPointSize(14)
        self.lblTitulo.setFont(font_titulo)
        self.lblTitulo.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lblTitulo.setText("Administradores")

        self.contenedorForm = QtWidgets.QWidget(parent=Form)
        self.contenedorForm.setGeometry(QtCore.QRect(20, 60, 760, 120))
        layout = QtWidgets.QFormLayout(self.contenedorForm)
        layout.setContentsMargins(0, 0, 0, 0)

        def fila(texto):
            lbl = QtWidgets.QLabel(texto, parent=self.contenedorForm)
            lbl.setFont(font_base)
            campo = QtWidgets.QLineEdit(parent=self.contenedorForm)
            campo.setFont(font_base)
            layout.addRow(lbl, campo)
            return campo

        self.txtUsuario = fila("Usuario:")
        self.txtContrasena = fila("Contraseña:")
        self.txtEmail = fila("Email:")

        font_btn = QtGui.QFont()
        font_btn.setFamily("Segoe UI")
        font_btn.setPointSize(11)

        self.btnGuardar = QtWidgets.QPushButton(parent=Form)
        self.btnGuardar.setGeometry(QtCore.QRect(470, 190, 150, 35))
        self.btnGuardar.setFont(font_btn)
        self.btnGuardar.setText("Agregar")
        self.btnGuardar.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))

        self.btnLimpiar = QtWidgets.QPushButton(parent=Form)
        self.btnLimpiar.setGeometry(QtCore.QRect(630, 190, 150, 35))
        self.btnLimpiar.setFont(font_base)
        self.btnLimpiar.setText("Limpiar")
        self.btnLimpiar.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))

        self.tblPersonal = QtWidgets.QTableWidget(parent=Form)
        self.tblPersonal.setGeometry(QtCore.QRect(20, 240, 760, 300))
        self.tblPersonal.setFont(font_base)
        self.tblPersonal.setColumnCount(3)
        self.tblPersonal.setHorizontalHeaderLabels(["Usuario", "Contraseña", "Email"])
        self.tblPersonal.setEditTriggers(QtWidgets.QAbstractItemView.EditTrigger.NoEditTriggers)
        self.tblPersonal.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectionBehavior.SelectRows)
        self.tblPersonal.setAlternatingRowColors(True)
        self.tblPersonal.horizontalHeader().setStretchLastSection(True)

        self.txtEliminarUsuario = QtWidgets.QLineEdit(parent=Form)
        self.txtEliminarUsuario.setGeometry(QtCore.QRect(20, 553, 440, 35))
        self.txtEliminarUsuario.setFont(font_base)
        self.txtEliminarUsuario.setPlaceholderText("Usuario a eliminar")

        self.btnEliminar = QtWidgets.QPushButton(parent=Form)
        self.btnEliminar.setGeometry(QtCore.QRect(470, 553, 150, 35))
        self.btnEliminar.setFont(font_btn)
        self.btnEliminar.setText("Eliminar")
        self.btnEliminar.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))

        self.btnRefrescar = QtWidgets.QPushButton(parent=Form)
        self.btnRefrescar.setGeometry(QtCore.QRect(630, 553, 150, 35))
        self.btnRefrescar.setFont(font_base)
        self.btnRefrescar.setText("Refrescar")
        self.btnRefrescar.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
