# Form implementation generated from reading ui file 'AceptarEstudiante.ui'
#
# Created by: PyQt6 UI code generator 6.11.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_AceptarEstudiante(object):
    def setupUi(self, Form):
        Form.setObjectName("frmAceptarEstudiante")
        Form.resize(800, 600)
        Form.setMinimumSize(QtCore.QSize(800, 600))
        Form.setMaximumSize(QtCore.QSize(800, 600))
        Form.setWindowTitle("Aceptar Estudiante de Terna")

        font_base = QtGui.QFont()
        font_base.setFamily("Segoe UI")
        font_base.setPointSize(11)

        font_btn = QtGui.QFont()
        font_btn.setFamily("Segoe UI")
        font_btn.setPointSize(11)

        self.lblTitulo = QtWidgets.QLabel(parent=Form)
        self.lblTitulo.setGeometry(QtCore.QRect(200, 10, 400, 40))
        font_titulo = QtGui.QFont()
        font_titulo.setFamily("Segoe UI")
        font_titulo.setPointSize(14)
        self.lblTitulo.setFont(font_titulo)
        self.lblTitulo.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lblTitulo.setText("Postulaciones en Terna (Enviadas)")

        self.tblTernasEnviadas = QtWidgets.QTableWidget(parent=Form)
        self.tblTernasEnviadas.setGeometry(QtCore.QRect(20, 60, 760, 350))
        self.tblTernasEnviadas.setFont(font_base)
        self.tblTernasEnviadas.setColumnCount(5)
        self.tblTernasEnviadas.setHorizontalHeaderLabels(
            ["ID Postulación", "Estudiante", "Ciclo", "Oferta/Puesto", "Estado"])
        self.tblTernasEnviadas.setEditTriggers(QtWidgets.QAbstractItemView.EditTrigger.NoEditTriggers)
        self.tblTernasEnviadas.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectionBehavior.SelectRows)
        self.tblTernasEnviadas.setAlternatingRowColors(True)
        self.tblTernasEnviadas.horizontalHeader().setStretchLastSection(True)
        self.tblTernasEnviadas.horizontalHeader().setFont(font_base)

        self.lblIdPostulacion = QtWidgets.QLabel(parent=Form)
        self.lblIdPostulacion.setGeometry(QtCore.QRect(20, 440, 120, 30))
        self.lblIdPostulacion.setFont(font_base)
        self.lblIdPostulacion.setText("ID Postulación:")

        self.txtIdPostulacionAceptar = QtWidgets.QLineEdit(parent=Form)
        self.txtIdPostulacionAceptar.setGeometry(QtCore.QRect(150, 440, 200, 30))
        self.txtIdPostulacionAceptar.setFont(font_base)
        self.txtIdPostulacionAceptar.setPlaceholderText("ID a aceptar")

        self.btnAceptarEstudiante = QtWidgets.QPushButton(parent=Form)
        self.btnAceptarEstudiante.setGeometry(QtCore.QRect(390, 435, 200, 40))
        self.btnAceptarEstudiante.setFont(font_btn)
        self.btnAceptarEstudiante.setText("Aceptar Estudiante")
        self.btnAceptarEstudiante.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))

        self.btnRefrescarAceptar = QtWidgets.QPushButton(parent=Form)
        self.btnRefrescarAceptar.setGeometry(QtCore.QRect(620, 500, 160, 35))
        self.btnRefrescarAceptar.setFont(font_base)
        self.btnRefrescarAceptar.setText("Refrescar Tabla")
        self.btnRefrescarAceptar.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
