# Form implementation generated from reading ui file 'CrearOferta.ui'
#
# Created by: PyQt6 UI code generator 6.11.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_CrearOferta(object):
    def setupUi(self, Form):
        Form.setObjectName("frmCrearOferta")
        Form.resize(800, 600)
        Form.setMinimumSize(QtCore.QSize(800, 600))
        Form.setMaximumSize(QtCore.QSize(800, 600))
        Form.setWindowTitle("Crear Oferta de Práctica")

        font_base = QtGui.QFont()
        font_base.setFamily("Segoe UI")
        font_base.setPointSize(11)

        font_btn = QtGui.QFont()
        font_btn.setFamily("Segoe UI")
        font_btn.setPointSize(11)

        self.lblTitulo = QtWidgets.QLabel(parent=Form)
        self.lblTitulo.setGeometry(QtCore.QRect(200, 20, 400, 40))
        font_titulo = QtGui.QFont()
        font_titulo.setFamily("Segoe UI")
        font_titulo.setPointSize(14)
        self.lblTitulo.setFont(font_titulo)
        self.lblTitulo.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lblTitulo.setText("Crear Nueva Oferta de Práctica")

        self.lblEmpresa = QtWidgets.QLabel(parent=Form)
        self.lblEmpresa.setGeometry(QtCore.QRect(100, 100, 120, 30))
        self.lblEmpresa.setFont(font_base)
        self.lblEmpresa.setText("Empresa:")

        self.lblEmpresaNombre = QtWidgets.QLabel(parent=Form)
        self.lblEmpresaNombre.setGeometry(QtCore.QRect(230, 100, 400, 30))
        font_emp = QtGui.QFont()
        font_emp.setFamily("Segoe UI")
        font_emp.setPointSize(11)
        self.lblEmpresaNombre.setFont(font_emp)
        self.lblEmpresaNombre.setText("")

        self.lblPuesto = QtWidgets.QLabel(parent=Form)
        self.lblPuesto.setGeometry(QtCore.QRect(100, 160, 120, 30))
        self.lblPuesto.setFont(font_base)
        self.lblPuesto.setText("Puesto:")

        self.txtPuesto = QtWidgets.QLineEdit(parent=Form)
        self.txtPuesto.setGeometry(QtCore.QRect(230, 160, 400, 30))
        self.txtPuesto.setFont(font_base)
        self.txtPuesto.setPlaceholderText("Nombre del puesto")

        self.lblDescripcion = QtWidgets.QLabel(parent=Form)
        self.lblDescripcion.setGeometry(QtCore.QRect(100, 220, 120, 30))
        self.lblDescripcion.setFont(font_base)
        self.lblDescripcion.setText("Descripción:")

        self.txaDescripcion = QtWidgets.QTextEdit(parent=Form)
        self.txaDescripcion.setGeometry(QtCore.QRect(230, 220, 400, 120))
        self.txaDescripcion.setFont(font_base)
        self.txaDescripcion.setPlaceholderText("Descripción de la oferta...")

        self.btnCrearOferta = QtWidgets.QPushButton(parent=Form)
        self.btnCrearOferta.setGeometry(QtCore.QRect(310, 380, 200, 40))
        self.btnCrearOferta.setFont(font_btn)
        self.btnCrearOferta.setText("Crear Oferta")
        self.btnCrearOferta.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))

        self.tblOfertas = QtWidgets.QTableWidget(parent=Form)
        self.tblOfertas.setGeometry(QtCore.QRect(20, 440, 760, 140))
        self.tblOfertas.setFont(font_base)
        self.tblOfertas.setColumnCount(5)
        self.tblOfertas.setHorizontalHeaderLabels(
            ["ID", "Empresa", "Puesto", "Descripción", "Fecha"])
        self.tblOfertas.setEditTriggers(QtWidgets.QAbstractItemView.EditTrigger.NoEditTriggers)
        self.tblOfertas.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectionBehavior.SelectRows)
        self.tblOfertas.setAlternatingRowColors(True)
        self.tblOfertas.horizontalHeader().setStretchLastSection(True)
        self.tblOfertas.horizontalHeader().setFont(font_base)
