# Form implementation generated from reading ui file 'Formulario2.ui'
#
# Created by: PyQt6 UI code generator 6.11.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Formulario2(object):
    def setupUi(self, Form):
        Form.setObjectName("frmFormulario2")
        Form.resize(820, 720)
        Form.setMinimumSize(QtCore.QSize(820, 720))
        Form.setWindowTitle("Formulario 2 - Evaluación Empresarial")

        font_base = QtGui.QFont()
        font_base.setFamily("Segoe UI")
        font_base.setPointSize(11)

        self.lblTitulo = QtWidgets.QLabel(parent=Form)
        self.lblTitulo.setGeometry(QtCore.QRect(210, 10, 400, 40))
        font_titulo = QtGui.QFont()
        font_titulo.setFamily("Segoe UI")
        font_titulo.setPointSize(14)
        self.lblTitulo.setFont(font_titulo)
        self.lblTitulo.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lblTitulo.setText("Formulario 2 - Evaluación Empresarial")

        self.cabecera = QtWidgets.QWidget(parent=Form)
        self.cabecera.setGeometry(QtCore.QRect(20, 55, 780, 120))
        layout = QtWidgets.QFormLayout(self.cabecera)
        layout.setContentsMargins(0, 0, 0, 0)

        def solo_lectura(texto):
            lbl = QtWidgets.QLabel(texto, parent=self.cabecera)
            lbl.setFont(font_base)
            val = QtWidgets.QLabel("", parent=self.cabecera)
            val.setFont(font_base)
            layout.addRow(lbl, val)
            return val

        self.lblEstudianteVal = solo_lectura("Estudiante:")
        self.lblEmpresaVal = solo_lectura("Empresa:")
        self.lblTutorVal = solo_lectura("Tutor Empresarial:")
        self.lblCargoTelVal = solo_lectura("Cargo / Teléfono:")

        self.lblPractica = QtWidgets.QLabel(parent=Form)
        self.lblPractica.setGeometry(QtCore.QRect(20, 185, 160, 30))
        self.lblPractica.setFont(font_base)
        self.lblPractica.setText("ID Práctica:")

        self.txtIdPractica = QtWidgets.QLineEdit(parent=Form)
        self.txtIdPractica.setGeometry(QtCore.QRect(180, 185, 150, 30))
        self.txtIdPractica.setFont(font_base)
        self.txtIdPractica.setPlaceholderText("ID")

        self.btnCargar = QtWidgets.QPushButton(parent=Form)
        self.btnCargar.setGeometry(QtCore.QRect(350, 185, 150, 30))
        self.btnCargar.setFont(font_base)
        self.btnCargar.setText("Cargar Datos")
        self.btnCargar.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))

        self.lblFInicio = QtWidgets.QLabel(parent=Form)
        self.lblFInicio.setGeometry(QtCore.QRect(20, 225, 130, 30))
        self.lblFInicio.setFont(font_base)
        self.lblFInicio.setText("Inicio real:")
        self.dtFechaRealInicio = QtWidgets.QDateEdit(parent=Form)
        self.dtFechaRealInicio.setGeometry(QtCore.QRect(150, 225, 140, 30))
        self.dtFechaRealInicio.setFont(font_base)
        self.dtFechaRealInicio.setCalendarPopup(True)
        self.dtFechaRealInicio.setDisplayFormat("dd/MM/yyyy")

        self.lblFFin = QtWidgets.QLabel(parent=Form)
        self.lblFFin.setGeometry(QtCore.QRect(310, 225, 100, 30))
        self.lblFFin.setFont(font_base)
        self.lblFFin.setText("Fin real:")
        self.dtFechaRealFin = QtWidgets.QDateEdit(parent=Form)
        self.dtFechaRealFin.setGeometry(QtCore.QRect(400, 225, 140, 30))
        self.dtFechaRealFin.setFont(font_base)
        self.dtFechaRealFin.setCalendarPopup(True)
        self.dtFechaRealFin.setDisplayFormat("dd/MM/yyyy")

        self.lblHoras = QtWidgets.QLabel(parent=Form)
        self.lblHoras.setGeometry(QtCore.QRect(560, 225, 130, 30))
        self.lblHoras.setFont(font_base)
        self.lblHoras.setText("Horas cumplidas:")
        self.spnHorasCumplidas = QtWidgets.QSpinBox(parent=Form)
        self.spnHorasCumplidas.setGeometry(QtCore.QRect(690, 225, 110, 30))
        self.spnHorasCumplidas.setFont(font_base)
        self.spnHorasCumplidas.setMaximum(500)

        self.tblRubrica = QtWidgets.QTableWidget(parent=Form)
        self.tblRubrica.setGeometry(QtCore.QRect(20, 265, 780, 250))
        self.tblRubrica.setFont(font_base)
        self.tblRubrica.setColumnCount(2)
        self.tblRubrica.setHorizontalHeaderLabels(["Habilidad", "Calificación"])
        self.tblRubrica.setColumnWidth(0, 560)
        self.tblRubrica.setColumnWidth(1, 200)
        self.tblRubrica.setEditTriggers(QtWidgets.QAbstractItemView.EditTrigger.NoEditTriggers)
        self.tblRubrica.setWordWrap(True)

        self.lblProductos = QtWidgets.QLabel(parent=Form)
        self.lblProductos.setGeometry(QtCore.QRect(20, 520, 360, 25))
        self.lblProductos.setFont(font_base)
        self.lblProductos.setText("Productos relevantes:")
        self.txaProductosRelevantes = QtWidgets.QTextEdit(parent=Form)
        self.txaProductosRelevantes.setGeometry(QtCore.QRect(20, 548, 380, 100))
        self.txaProductosRelevantes.setFont(font_base)

        self.lblAspectos = QtWidgets.QLabel(parent=Form)
        self.lblAspectos.setGeometry(QtCore.QRect(420, 520, 360, 25))
        self.lblAspectos.setFont(font_base)
        self.lblAspectos.setText("Aspectos relevantes:")
        self.txaAspectosRelevantes = QtWidgets.QTextEdit(parent=Form)
        self.txaAspectosRelevantes.setGeometry(QtCore.QRect(420, 548, 380, 100))
        self.txaAspectosRelevantes.setFont(font_base)

        font_btn = QtGui.QFont()
        font_btn.setFamily("Segoe UI")
        font_btn.setPointSize(11)

        self.btnGuardarEvaluacion = QtWidgets.QPushButton(parent=Form)
        self.btnGuardarEvaluacion.setGeometry(QtCore.QRect(200, 665, 200, 40))
        self.btnGuardarEvaluacion.setFont(font_btn)
        self.btnGuardarEvaluacion.setText("Guardar Evaluación")
        self.btnGuardarEvaluacion.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))

        self.btnLimpiar = QtWidgets.QPushButton(parent=Form)
        self.btnLimpiar.setGeometry(QtCore.QRect(420, 665, 200, 40))
        self.btnLimpiar.setFont(font_btn)
        self.btnLimpiar.setText("Limpiar")
        self.btnLimpiar.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
