# Form implementation generated from reading ui file 'ListarPracticasActivas.ui'
#
# Created by: PyQt6 UI code generator 6.11.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_ListarPracticasActivas(object):
    def setupUi(self, Form):
        Form.setObjectName("frmListarPracticasActivas")
        Form.resize(800, 600)
        Form.setMinimumSize(QtCore.QSize(800, 600))
        Form.setWindowTitle("Prácticas Activas")

        font_base = QtGui.QFont()
        font_base.setFamily("Segoe UI")
        font_base.setPointSize(11)

        self.lblTitulo = QtWidgets.QLabel(parent=Form)
        self.lblTitulo.setGeometry(QtCore.QRect(200, 10, 400, 40))
        font_titulo = QtGui.QFont()
        font_titulo.setFamily("Segoe UI")
        font_titulo.setPointSize(14)
        self.lblTitulo.setFont(font_titulo)
        self.lblTitulo.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lblTitulo.setText("Mis Prácticas Activas")

        self.tblPracticas = QtWidgets.QTableWidget(parent=Form)
        self.tblPracticas.setGeometry(QtCore.QRect(20, 60, 760, 470))
        self.tblPracticas.setFont(font_base)
        self.tblPracticas.setColumnCount(5)
        self.tblPracticas.setHorizontalHeaderLabels(
            ["ID Práctica", "Estudiante", "Tutor Académico", "Estado", "Fecha Inicio"])
        self.tblPracticas.setColumnWidth(0, 100)
        self.tblPracticas.setColumnWidth(1, 200)
        self.tblPracticas.setColumnWidth(2, 180)
        self.tblPracticas.setColumnWidth(3, 160)
        self.tblPracticas.setEditTriggers(QtWidgets.QAbstractItemView.EditTrigger.NoEditTriggers)
        self.tblPracticas.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectionBehavior.SelectRows)
        self.tblPracticas.setAlternatingRowColors(True)
        self.tblPracticas.horizontalHeader().setStretchLastSection(True)

        self.btnRefrescar = QtWidgets.QPushButton(parent=Form)
        self.btnRefrescar.setGeometry(QtCore.QRect(620, 545, 160, 35))
        self.btnRefrescar.setFont(font_base)
        self.btnRefrescar.setText("Refrescar")
        self.btnRefrescar.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
