# Form implementation generated from reading ui file 'VistaTutorEmpresarialPrincipal.ui'
#
# Created by: PyQt6 UI code generator 6.11.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_frmTutorEmpresarial(object):
    def setupUi(self, frmTutorEmpresarial):
        frmTutorEmpresarial.setObjectName("frmTutorEmpresarial")
        frmTutorEmpresarial.resize(800, 600)
        frmTutorEmpresarial.setWindowTitle("Coordinador / Tutor Empresarial")

        self.centralwidget = QtWidgets.QWidget(parent=frmTutorEmpresarial)
        self.lblImagen = QtWidgets.QLabel(parent=self.centralwidget)
        self.lblImagen.setGeometry(QtCore.QRect(220, 140, 361, 341))
        self.lblImagen.setText("")
        self.lblImagen.setScaledContents(True)

        self.widget = QtWidgets.QWidget(parent=self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(0, 90, 801, 33))
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.addItem(QtWidgets.QSpacerItem(
            40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum))
        self.lblTitulo = QtWidgets.QLabel(parent=self.widget)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        self.lblTitulo.setFont(font)
        self.lblTitulo.setText("Panel del Tutor Empresarial")
        self.horizontalLayout.addWidget(self.lblTitulo)
        self.horizontalLayout.addItem(QtWidgets.QSpacerItem(
            40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum))
        frmTutorEmpresarial.setCentralWidget(self.centralwidget)

        self.menubar = QtWidgets.QMenuBar(parent=frmTutorEmpresarial)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 31))
        font_menu = QtGui.QFont()
        font_menu.setPointSize(11)
        self.menubar.setFont(font_menu)
        self.mnuOfertas = QtWidgets.QMenu(parent=self.menubar)
        self.mnuOfertas.setTitle("Ofertas")
        self.mnuPracticas = QtWidgets.QMenu(parent=self.menubar)
        self.mnuPracticas.setTitle("Prácticas")
        self.mnuSistema = QtWidgets.QMenu(parent=self.menubar)
        self.mnuSistema.setTitle("Sistema")
        frmTutorEmpresarial.setMenuBar(self.menubar)

        self.statusbar = QtWidgets.QStatusBar(parent=frmTutorEmpresarial)
        frmTutorEmpresarial.setStatusBar(self.statusbar)
        self.tlbPrincipal = QtWidgets.QToolBar(parent=frmTutorEmpresarial)
        frmTutorEmpresarial.addToolBar(QtCore.Qt.ToolBarArea.TopToolBarArea, self.tlbPrincipal)

        self.actCrearOferta = QtGui.QAction(parent=frmTutorEmpresarial)
        self.actCrearOferta.setText("Crear Oferta")
        self.actRecibirTernas = QtGui.QAction(parent=frmTutorEmpresarial)
        self.actRecibirTernas.setText("Recibir Ternas")
        self.actFormulario2 = QtGui.QAction(parent=frmTutorEmpresarial)
        self.actFormulario2.setText("Evaluación Empresarial")
        self.actListarPracticas = QtGui.QAction(parent=frmTutorEmpresarial)
        self.actListarPracticas.setText("Listar Prácticas Activas")
        self.actInformacion = QtGui.QAction(parent=frmTutorEmpresarial)
        self.actInformacion.setText("Información")
        self.actSalir = QtGui.QAction(parent=frmTutorEmpresarial)
        self.actSalir.setText("Salir")

        self.mnuOfertas.addAction(self.actCrearOferta)
        self.mnuPracticas.addAction(self.actListarPracticas)
        self.mnuPracticas.addAction(self.actRecibirTernas)
        self.mnuPracticas.addAction(self.actFormulario2)
        self.mnuSistema.addAction(self.actInformacion)
        self.mnuSistema.addSeparator()
        self.mnuSistema.addAction(self.actSalir)
        self.menubar.addAction(self.mnuSistema.menuAction())
        self.menubar.addAction(self.mnuOfertas.menuAction())
        self.menubar.addAction(self.mnuPracticas.menuAction())

        self.tlbPrincipal.addAction(self.actCrearOferta)
        self.tlbPrincipal.addAction(self.actListarPracticas)
        self.tlbPrincipal.addAction(self.actRecibirTernas)
        self.tlbPrincipal.addAction(self.actFormulario2)

        QtCore.QMetaObject.connectSlotsByName(frmTutorEmpresarial)
